language: perl
perl:
    - "5.36"
    - "5.30"
    - "5.20"
    - "5.10"
env:
  global:
    - PERL_CPANM_OPT="--notest --force --skip-satisfied"
before_install:
    - "cpanm JIP::ClassField@0.05"
install:
    - "perl Makefile.PL && make test"
sudo: false
notifications:
    email: false

